import crypto from 'crypto';

/**
 * Generate MD5 hash for Mondial Relay API1 security
 * The hash is generated by concatenating all parameters in the correct order
 * and then hashing with the private key
 */
export function generateMD5Hash(data: string): string {
    return crypto.createHash('md5').update(data, 'utf8').digest('hex').toUpperCase();
}

/**
 * Generate security key for Point Relais search (WSI4_PointRelais_Recherche)
 * Order: [Enseigne][Pays][NumPointRelais][CP][Latitude][Longitude][Taille][Poids][Action][DelaiEnvoi][RayonRecherche][NombreResultats][CLE PRIVEE]
 */
export function generatePointRelaisSearchSecurityKey(params: {
    enseigne: string;
    pays: string;
    numPointRelais?: string;
    cp?: string;
    latitude?: string;
    longitude?: string;
    taille?: string;
    poids?: string;
    action?: string;
    delaiEnvoi?: string;
    rayonRecherche?: string;
    nombreResultats: string;
    privateKey: string;
}): string {
    const concatenated = [
        params.enseigne,
        params.pays,
        params.numPointRelais || '',
        params.cp || '',
        params.latitude || '',
        params.longitude || '',
        params.taille || '',
        params.poids || '',
        params.action || '',
        params.delaiEnvoi || '',
        params.rayonRecherche || '',
        params.nombreResultats,
        params.privateKey,
    ].join('');

    return generateMD5Hash(concatenated);
}

/**
 * Generate security key for postal code search (WSI2_RechercheCP)
 * Order: [Enseigne][Pays][Ville][CP][NbResult][CLE PRIVEE]
 */
export function generatePostalCodeSearchSecurityKey(params: {
    enseigne: string;
    pays: string;
    ville: string;
    cp?: string;
    nbResult: string;
    privateKey: string;
}): string {
    const concatenated = [
        params.enseigne,
        params.pays,
        params.ville,
        params.cp || '',
        params.nbResult,
        params.privateKey,
    ].join('');

    return generateMD5Hash(concatenated);
}

/**
 * Generate security key for tracking (WSI2_TracingColisDetaille)
 * Order: [Enseigne][Expedition][Langue][CLE PRIVEE]
 */
export function generateTrackingSecurityKey(params: {
    enseigne: string;
    expedition: string;
    langue: string;
    privateKey: string;
}): string {
    const concatenated = [
        params.enseigne,
        params.expedition,
        params.langue,
        params.privateKey,
    ].join('');

    return generateMD5Hash(concatenated);
}

/**
 * Format GPS coordinates to Mondial Relay format: -?XX.XXXXXXX (11 chars)
 */
export function formatGPSCoordinate(coordinate: number): string {
    const formatted = coordinate.toFixed(7);
    // Ensure it's exactly 11 characters
    if (formatted.length > 11) {
        return formatted.substring(0, 11);
    }
    return formatted.padStart(11, '0');
}

/**
 * Validate Point Relais ID format (6 digits)
 */
export function isValidPointRelaisId(id: string): boolean {
    return /^[0-9]{6}$/.test(id);
}

/**
 * Validate shipment number format (8 digits)
 */
export function isValidShipmentNumber(number: string): boolean {
    return /^[0-9]{8}$/.test(number);
}
