// Auto-generated product data - DO NOT EDIT MANUALLY
// Generated on: 2026-02-04T20:40:37.178Z
// Total products: 75
// Each color variant is a separate product

export interface Product {
    id: number;
    name: string;
    price: string;
    priceNumber: number;
    variants: string[];
    brand: string;
    category: string;
    bikeType: string;
    description: string;
    features: string[];
    compatibility: string[];
    inStock: boolean;
    color: string;
    colorHex: string;
    image: string;
    stock: number;
    displacements: number[];
    yearRange: string;
    yearStart: number;
    yearEnd: number;
}

const PRODUCT_DESCRIPTION = `Nos protections sont avant tout conçues pour apporter un maximum de GRIP à votre moto, afin d'améliorer le contrôle et les sensations de pilotage.

Elles protègent également efficacement le cadre contre les rayures, l'usure et les impacts, tout en préservant sa valeur de revente.`;

const PRODUCT_FEATURES = [
    "Antidérapant",
    "Sur mesure",
    "Protège le cadre",
    "Épaisseur : 1 mm",
    "Facile à installer et à remplacer",
    "Testé et approuvé par des pilotes professionnels",
    "Réduit l'effort nécessaire pour tenir la moto"
];

export const products: Product[] = [
    {
        id: 1,
        name: "BETA 350RR 2023 RR2T250-300 24-25 RR4T350-450 24-25 RX300 2025 - Grip de protection plastique d'ORIGINE - Gris",
        price: "12,99 €",
        priceNumber: 12.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "BETA",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["300cc, 350cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/beta-350rr-2023-rr2t250-300-24-25-rr4t350-450-24-25-rx300-2025-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [300, 350, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 2,
        name: "BETA 350RR 2023 RR2T250-300 24-25 RR4T350-450 24-25 RX300 2025 - Grip de protection plastique d'ORIGINE - Noir",
        price: "12,99 €",
        priceNumber: 12.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "BETA",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["300cc, 350cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/beta-350rr-2023-rr2t250-300-24-25-rr4t350-450-24-25-rx300-2025-grip-de-protection-plastique-d-origine-noir.svg",
        stock: 20,
        displacements: [300, 350, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 3,
        name: "BETA 350RR 2023 RR2T250-300 24-25 RR4T350-450 24-25 RX300 2025 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "BETA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["300cc, 350cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/beta-350rr-2023-rr2t250-300-24-25-rr4t350-450-24-25-rx300-2025-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [300, 350, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 4,
        name: "FANTIC XXF250 21-25  XXF450 21-25 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "FANTIC",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/fantic-xxf250-21-25-xxf450-21-25-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [],
        yearRange: "2021-2025",
        yearStart: 2021,
        yearEnd: 2025,
    },
    {
        id: 5,
        name: "FANTIC XXF250 21-25  XXF450 21-25 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "FANTIC",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/fantic-xxf250-21-25-xxf450-21-25-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "2021-2025",
        yearStart: 2021,
        yearEnd: 2025,
    },
    {
        id: 6,
        name: "GASGAS 125-250MC 250-450MCF 24-25 - Grip de protection plastique d'ORIGINE - Gris",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "GASGAS",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/gasgas-125-250mc-250-450mcf-24-25-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [125, 250, 450],
        yearRange: "2024-2050",
        yearStart: 2024,
        yearEnd: 2050,
    },
    {
        id: 7,
        name: "GASGAS 125-250MC 250-450MCF 24-25 - Grip de protection plastique d'ORIGINE - Noir",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "GASGAS",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/gasgas-125-250mc-250-450mcf-24-25-grip-de-protection-plastique-d-origine-noir.svg",
        stock: 20,
        displacements: [125, 250, 450],
        yearRange: "2024-2050",
        yearStart: 2024,
        yearEnd: 2050,
    },
    {
        id: 8,
        name: "GASGAS 125-250MC 250-450MCF 24-25 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "GASGAS",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/gasgas-125-250mc-250-450mcf-24-25-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [125, 250, 450],
        yearRange: "2024-2050",
        yearStart: 2024,
        yearEnd: 2050,
    },
    {
        id: 9,
        name: "HONDA 450CRF 09-12 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "HONDA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/honda-450crf-09-12-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [450],
        yearRange: "2009-2012",
        yearStart: 2009,
        yearEnd: 2012,
    },
    {
        id: 10,
        name: "HONDA CRF250R 22-25  CRF450R 21-25 - Protection de cadre - Gris",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "HONDA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/honda-crf250r-22-25-crf450r-21-25-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2021-2025",
        yearStart: 2021,
        yearEnd: 2025,
    },
    {
        id: 11,
        name: "HONDA CRF250R 22-25  CRF450R 21-25 - Protection de cadre - Noir",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "HONDA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/honda-crf250r-22-25-crf450r-21-25-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2021-2025",
        yearStart: 2021,
        yearEnd: 2025,
    },
    {
        id: 12,
        name: "HONDA CRF250R 22-25  CRF450R 21-25 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "HONDA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/honda-crf250r-22-25-crf450r-21-25-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2021-2025",
        yearStart: 2021,
        yearEnd: 2025,
    },
    {
        id: 13,
        name: "HUSQVARNA 125-300TC 250-450FC 23-25 - Grip de protection plastique d'ORIGINE - Gris",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "HUSQVARNA",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 300cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/husqvarna-125-300tc-250-450fc-23-25-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [125, 250, 300, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 14,
        name: "HUSQVARNA 125-300TC 250-450FC 23-25 - Grip de protection plastique d'ORIGINE - Noir",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "HUSQVARNA",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 300cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/husqvarna-125-300tc-250-450fc-23-25-grip-de-protection-plastique-d-origine-noir.svg",
        stock: 20,
        displacements: [125, 250, 300, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 15,
        name: "KAWASAKI 125KX 03-08 250KX 03-04 - Protection de cadre - Gris",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kawasaki-125kx-03-08-250kx-03-04-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [125, 250],
        yearRange: "2003-2008",
        yearStart: 2003,
        yearEnd: 2008,
    },
    {
        id: 16,
        name: "KAWASAKI 125KX 03-08 250KX 03-04 - Protection de cadre - Noir",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kawasaki-125kx-03-08-250kx-03-04-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [125, 250],
        yearRange: "2003-2008",
        yearStart: 2003,
        yearEnd: 2008,
    },
    {
        id: 17,
        name: "KAWASAKI 250KXF 15-20 - Protection de cadre - Noir",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kawasaki-250kxf-15-20-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250],
        yearRange: "2015-2020",
        yearStart: 2015,
        yearEnd: 2020,
    },
    {
        id: 18,
        name: "KAWASAKI 250KXF 15-20 - Protection de cadre - Gris",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kawasaki-250kxf-15-20-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250],
        yearRange: "2015-2020",
        yearStart: 2015,
        yearEnd: 2020,
    },
    {
        id: 19,
        name: "KAWASAKI 250KXF 15-20 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "KAWASAKI",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/kawasaki-250kxf-15-20-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [250],
        yearRange: "2015-2020",
        yearStart: 2015,
        yearEnd: 2020,
    },
    {
        id: 20,
        name: "KAWASAKI 250KXF 2025 450KXF 24-25 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kawasaki-250kxf-2025-450kxf-24-25-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2024-2025",
        yearStart: 2024,
        yearEnd: 2025,
    },
    {
        id: 21,
        name: "KAWASAKI 250KXF 2025 450KXF 24-25 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kawasaki-250kxf-2025-450kxf-24-25-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2024-2025",
        yearStart: 2024,
        yearEnd: 2025,
    },
    {
        id: 22,
        name: "KAWASAKI 250KXF 21-24 450KXF 19-23 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kawasaki-250kxf-21-24-450kxf-19-23-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2019-2024",
        yearStart: 2019,
        yearEnd: 2024,
    },
    {
        id: 23,
        name: "KAWASAKI 250KXF 21-24 450KXF 19-23 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kawasaki-250kxf-21-24-450kxf-19-23-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2019-2024",
        yearStart: 2019,
        yearEnd: 2024,
    },
    {
        id: 24,
        name: "KAWASAKI 250KXF 21-24 450KXF 19-23 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "KAWASAKI",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/kawasaki-250kxf-21-24-450kxf-19-23-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2019-2024",
        yearStart: 2019,
        yearEnd: 2024,
    },
    {
        id: 25,
        name: "KOVE 450 RALLY 24-26 - Protection de cadre - Gris",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "KOVE",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kove-450-rally-24-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [450],
        yearRange: "2024-2026",
        yearStart: 2024,
        yearEnd: 2026,
    },
    {
        id: 26,
        name: "KOVE 450 RALLY 24-26 - Protection de cadre - Noir",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "KOVE",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kove-450-rally-24-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [450],
        yearRange: "2024-2026",
        yearStart: 2024,
        yearEnd: 2026,
    },
    {
        id: 27,
        name: "KTM 125-150SX 16-18 250SX 17-18 250-450SXF - Grip de protection plastique d'ORIGINE - Gris",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "KTM",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 150cc, 250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/ktm-125-150sx-16-18-250sx-17-18-250-450sxf-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [125, 150, 250, 450],
        yearRange: "2015-2050",
        yearStart: 2015,
        yearEnd: 2050,
    },
    {
        id: 28,
        name: "KTM 125-150SX 16-18 250SX 17-18 250-450SXF - Grip de protection plastique d'ORIGINE - Noir",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "KTM",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 150cc, 250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/ktm-125-150sx-16-18-250sx-17-18-250-450sxf-grip-de-protection-plastique-d-origine-noir.svg",
        stock: 20,
        displacements: [125, 150, 250, 450],
        yearRange: "2015-2050",
        yearStart: 2015,
        yearEnd: 2050,
    },
    {
        id: 29,
        name: "KTM 125-150SX 16-18 250SX 17-18 250-450SXF - Protection de cadre - Gris",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "KTM",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 150cc, 250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/ktm-125-150sx-16-18-250sx-17-18-250-450sxf-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [125, 150, 250, 450],
        yearRange: "2015-2050",
        yearStart: 2015,
        yearEnd: 2050,
    },
    {
        id: 30,
        name: "KTM 125-150SX 16-18 250SX 17-18 250-450SXF - Protection de cadre - Noir",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "KTM",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 150cc, 250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/ktm-125-150sx-16-18-250sx-17-18-250-450sxf-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [125, 150, 250, 450],
        yearRange: "2015-2050",
        yearStart: 2015,
        yearEnd: 2050,
    },
    {
        id: 31,
        name: "KTM 125-150SX 16-18 250SX 17-18 250-450SXF - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "KTM",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 150cc, 250cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/ktm-125-150sx-16-18-250sx-17-18-250-450sxf-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [125, 150, 250, 450],
        yearRange: "2015-2050",
        yearStart: 2015,
        yearEnd: 2050,
    },
    {
        id: 32,
        name: "KTM 125-300SX 250-450SXF 23-26 - Protection de cadre - Gris",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "KTM",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 300cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/ktm-125-300sx-250-450sxf-23-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [125, 250, 300, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 33,
        name: "KTM 125-300SX 250-450SXF 23-26 - Protection de cadre - Noir",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "KTM",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 300cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/ktm-125-300sx-250-450sxf-23-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [125, 250, 300, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 34,
        name: "KTM 125-300SX 250-450SXF 23-26 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "KTM",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc, 300cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/ktm-125-300sx-250-450sxf-23-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [125, 250, 300, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 35,
        name: "KTM 85SX 18-24 - Grip de protection plastique d'ORIGINE - Gris",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "KTM",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["85cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/ktm-85sx-18-24-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [85],
        yearRange: "2018-2024",
        yearStart: 2018,
        yearEnd: 2024,
    },
    {
        id: 87,
        name: "KTM 85SX 18-24 - Grip de protection plastique d'ORIGINE - Noir",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "KTM",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["85cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/ktm-85sx-18-24-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [85],
        yearRange: "2018-2024",
        yearStart: 2018,
        yearEnd: 2024,
    },
    {
        id: 36,
        name: "STARK MX 22-26 EX 24-26 - Protection de cadre - Droite",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de cadre"],
        brand: "Stark Varg",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Droite",
        colorHex: "#CCCCCC",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-cadre-droite.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 37,
        name: "STARK MX 22-26 EX 24-26 - Protection de cadre - Gauche",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de cadre"],
        brand: "Stark Varg",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gauche",
        colorHex: "#CCCCCC",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-cadre-gauche.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 38,
        name: "STARK MX 22-26 EX 24-26 - Protection de cadre - Gris",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de cadre"],
        brand: "Stark Varg",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 39,
        name: "STARK MX 22-26 EX 24-26 - Protection de cadre - Noir",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de cadre"],
        brand: "Stark Varg",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 40,
        name: "STARK MX 22-26 EX 24-26 - Protection de carter - Droite",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de carter"],
        brand: "Stark Varg",
        category: "Protection de carter",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Droite",
        colorHex: "#CCCCCC",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-carter-droite.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 41,
        name: "STARK MX 22-26 EX 24-26 - Protection de carter - Gris",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de carter"],
        brand: "Stark Varg",
        category: "Protection de carter",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-carter-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 42,
        name: "STARK MX 22-26 EX 24-26 - Protection de carter - Noir",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de carter"],
        brand: "Stark Varg",
        category: "Protection de carter",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-carter-noir.svg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 43,
        name: "STARK MX 22-26 EX 24-26 - Protection de plaque latérale - Droite",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de plaque latérale"],
        brand: "Stark Varg",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Droite",
        colorHex: "#CCCCCC",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-plaque-laterale-droite.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 44,
        name: "STARK MX 22-26 EX 24-26 - Protection de plaque latérale - Gauche",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de plaque latérale"],
        brand: "Stark Varg",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gauche",
        colorHex: "#CCCCCC",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-plaque-laterale-gauche.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 45,
        name: "STARK MX 22-26 EX 24-26 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "Stark Varg",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/stark-mx-22-26-ex-24-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 46,
        name: "SUZUKI 125RM 01-12  250RM 01-08 - Protection de cadre - Gris",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/suzuki-125rm-01-12-250rm-01-08-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [125, 250],
        yearRange: "2001-2012",
        yearStart: 2001,
        yearEnd: 2012,
    },
    {
        id: 47,
        name: "SUZUKI 125RM 01-12  250RM 01-08 - Protection de cadre - Noir",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/suzuki-125rm-01-12-250rm-01-08-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [125, 250],
        yearRange: "2001-2012",
        yearStart: 2001,
        yearEnd: 2012,
    },
    {
        id: 48,
        name: "SUZUKI 250RM 04-11 - Protection de cadre - Gris",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/suzuki-250rm-04-11-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250],
        yearRange: "2004-2011",
        yearStart: 2004,
        yearEnd: 2011,
    },
    {
        id: 49,
        name: "SUZUKI 250RMZ 19-26 450RMZ 18-26 - Protection de cadre - Gris",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/suzuki-250rmz-19-26-450rmz-18-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2018-2026",
        yearStart: 2018,
        yearEnd: 2026,
    },
    {
        id: 50,
        name: "SUZUKI 250RMZ 19-26 450RMZ 18-26 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/suzuki-250rmz-19-26-450rmz-18-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2018-2026",
        yearStart: 2018,
        yearEnd: 2026,
    },
    {
        id: 51,
        name: "SUZUKI RMZ 08-17 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/suzuki-rmz-08-17-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "2008-2017",
        yearStart: 2008,
        yearEnd: 2017,
    },
    {
        id: 52,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de cadre - Gris",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "TRIUMPH",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 53,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de cadre - Noir",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "TRIUMPH",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 54,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de cadre - Droite",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "TRIUMPH",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Droite",
        colorHex: "#CCCCCC",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-cadre-droite.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 55,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de cadre - Gauche",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "TRIUMPH",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gauche",
        colorHex: "#CCCCCC",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-cadre-gauche.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 56,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de plaque latérale - Droite",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "TRIUMPH",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Droite",
        colorHex: "#CCCCCC",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-plaque-laterale-droite.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 57,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de plaque latérale - Gauche",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "TRIUMPH",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gauche",
        colorHex: "#CCCCCC",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-plaque-laterale-gauche.jpeg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 58,
        name: "TRIUMPH TF250-X 2024-2025 TF450-X 2025 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "TRIUMPH",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/triumph-tf250-x-2024-2025-tf450-x-2025-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [],
        yearRange: "2020-2025",
        yearStart: 2020,
        yearEnd: 2025,
    },
    {
        id: 59,
        name: "YAMAHA Grip de protection maitre cylindre arrière WORKS CONNECTION - Grip de protection plastique d'ORIGINE - Gris",
        price: "5,00 €",
        priceNumber: 5.00,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "YAMAHA",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/yamaha-grip-de-protection-maitre-cylindre-arriere-works-connection-grip-de-protection-plastique-d-origine-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "N/A",
        yearStart: 2000,
        yearEnd: 2026,
    },
    {
        id: 60,
        name: "YAMAHA Grip de protection maitre cylindre arrière WORKS CONNECTION - Grip de protection plastique d'ORIGINE - Noir",
        price: "5,00 €",
        priceNumber: 5.00,
        variants: ["Grip de protection plastique d'ORIGINE"],
        brand: "YAMAHA",
        category: "Grip de protection plastique d'ORIGINE",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/yamaha-grip-de-protection-maitre-cylindre-arriere-works-connection-grip-de-protection-plastique-d-origine-noir.svg",
        stock: 20,
        displacements: [],
        yearRange: "N/A",
        yearStart: 2000,
        yearEnd: 2026,
    },
    {
        id: 61,
        name: "YAMAHA 125YZ 15-21 250YZ 15-21 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/yamaha-125yz-15-21-250yz-15-21-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [125, 250],
        yearRange: "2015-2021",
        yearStart: 2015,
        yearEnd: 2021,
    },
    {
        id: 62,
        name: "YAMAHA 125YZ 22-26 250YZ 22-26 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["125cc, 250cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/yamaha-125yz-22-26-250yz-22-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [125, 250],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 63,
        name: "YAMAHA 250-450YZF 06-09 - Protection de cadre - Gris",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/yamaha-250-450yzf-06-09-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2006-2050",
        yearStart: 2006,
        yearEnd: 2050,
    },
    {
        id: 64,
        name: "YAMAHA 250-450YZF 06-09 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/yamaha-250-450yzf-06-09-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2006-2050",
        yearStart: 2006,
        yearEnd: 2050,
    },
    {
        id: 65,
        name: "YAMAHA 65YZ 18-26 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["65cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/yamaha-65yz-18-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [65],
        yearRange: "2018-2026",
        yearStart: 2018,
        yearEnd: 2026,
    },
    {
        id: 66,
        name: "YAMAHA 85YZ 25-26 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["85cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/yamaha-85yz-25-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [85],
        yearRange: "2025-2026",
        yearStart: 2025,
        yearEnd: 2026,
    },
    {
        id: 67,
        name: "YAMAHA YZ125 05-25 YZ250 05-25 - Protection de cadre - Gris",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/yamaha-yz125-05-25-yz250-05-25-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [],
        yearRange: "2005-2025",
        yearStart: 2005,
        yearEnd: 2025,
    },
    {
        id: 68,
        name: "YAMAHA YZ125 05-25 YZ250 05-25 - Protection de cadre - Noir",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["Voir description"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/yamaha-yz125-05-25-yz250-05-25-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [],
        yearRange: "2005-2025",
        yearStart: 2005,
        yearEnd: 2025,
    },
    {
        id: 69,
        name: "YAMAHA YZ250F 19-23  YZ450F 18-22 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/yamaha-yz250f-19-23-yz450f-18-22-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2018-2023",
        yearStart: 2018,
        yearEnd: 2023,
    },
    {
        id: 70,
        name: "YAMAHA YZ250F 19-23  YZ450F 18-22 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/yamaha-yz250f-19-23-yz450f-18-22-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2018-2023",
        yearStart: 2018,
        yearEnd: 2023,
    },
    {
        id: 71,
        name: "YAMAHA YZ250F 24-26  YZ450F 23-26 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/yamaha-yz250f-24-26-yz450f-23-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2023-2026",
        yearStart: 2023,
        yearEnd: 2026,
    },
    {
        id: 72,
        name: "YAMAHA YZ250F 24-26  YZ450F 23-26 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/yamaha-yz250f-24-26-yz450f-23-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2023-2026",
        yearStart: 2023,
        yearEnd: 2026,
    },
    {
        id: 73,
        name: "YAMAHA YZ250F 24-26 YZ450F 23-26 - Protection de plaque latérale - Gauche 2",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Gauche 2",
        colorHex: "#CCCCCC",
        image: "/images/products/yamaha-yz250f-24-26-yz450f-23-26-protection-de-plaque-laterale-gauche-2.jpeg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2023-2026",
        yearStart: 2023,
        yearEnd: 2026,
    },
    {
        id: 74,
        name: "YAMAHA YZ250F 24-26 YZ450F 23-26 - Protection de plaque latérale - Transparent",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/yamaha-yz250f-24-26-yz450f-23-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2023-2026",
        yearStart: 2023,
        yearEnd: 2026,
    },
    {
        id: 75,
        name: "YAMAHA YZ250F 24-26 YZ450F 23-26 - Protection de plaque latérale - Droite",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de plaque latérale"],
        brand: "YAMAHA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["250cc, 450cc"],
        inStock: true,
        color: "Droite",
        colorHex: "#CCCCCC",
        image: "/images/products/yamaha-yz250f-24-26-yz450f-23-26-protection-de-plaque-laterale-droite.jpeg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2023-2026",
        yearStart: 2023,
        yearEnd: 2026,
    },
    {
        id: 84,
        name: "YAMAHA 250-450YZF 06-09 - Protection de cadre - Noir",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["YAMAHA 250-450YZF 06-09"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/yamaha-250-450yzf-06-09-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250, 450],
        yearRange: "2006-2050",
        yearStart: 2006,
        yearEnd: 2050,
    },
    {
        id: 85,
        name: "HUSQVARNA 125-300TC 23-25 250-450FC 23-24 - Protection de plaque latérale - Transparent",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection de plaque latérale"],
        brand: "HUSQVARNA",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["HUSQVARNA 125-300TC 23-25 250-450FC 23-24"],
        inStock: true,
        color: "Transparent",
        colorHex: "#CCCCCC",
        image: "/images/products/husqvarna-125-300tc-23-25-250-450fc-23-24-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [125, 250, 300, 450],
        yearRange: "2023-2050",
        yearStart: 2023,
        yearEnd: 2050,
    },
    {
        id: 86,
        name: "KOVE 450 RALLY 24-26 - Protection Thermique réservoir - Noir",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection Thermique réservoir"],
        brand: "KOVE",
        category: "Protection Thermique réservoir",
        bikeType: "Rally",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["KOVE 450 RALLY 24-26"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kove-450-rally-thermal-protection-installed-1.jpeg",
        stock: 20,
        displacements: [450],
        yearRange: "2024-2026",
        yearStart: 2024,
        yearEnd: 2026,
    },
    {
        id: 88,
        name: "HONDA 450CRF 09-12 - Protection de cadre - Gris",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "HONDA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["HONDA 450CRF 09-12"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/honda-450crf-09-12-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [450],
        yearRange: "2009-2012",
        yearStart: 2009,
        yearEnd: 2012,
    },
    {
        id: 89,
        name: "HONDA 450CRF 09-12 - Protection de cadre - Noir",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "HONDA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["HONDA 450CRF 09-12"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/honda-450crf-09-12-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [450],
        yearRange: "2009-2012",
        yearStart: 2009,
        yearEnd: 2012,
    },
    {
        id: 90,
        name: "KAWASAKI 250KX 05-08 - Protection de cadre - Gris",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["KAWASAKI 250KX 05-08"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kawasaki-250kx-05-08-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [250],
        yearRange: "2005-2008",
        yearStart: 2005,
        yearEnd: 2008,
    },
    {
        id: 91,
        name: "KOVE 450 RALLY 24-26 - Protection de carter embrayage - Noir",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de carter embrayage"],
        brand: "KOVE",
        category: "Protection de carter embrayage",
        bikeType: "Rally",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["KOVE 450 RALLY 24-26"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kove-450-rally-24-26-protection-de-carter-embrayage-noir.svg",
        stock: 20,
        displacements: [450],
        yearRange: "2024-2026",
        yearStart: 2024,
        yearEnd: 2026,
    },
    {
        id: 92,
        name: "KOVE 800X 25-26 - Protection de cadre - Gris",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection de cadre"],
        brand: "KOVE",
        category: "Protection de cadre",
        bikeType: "Adventure",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["KOVE 800X 25-26"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/kove-800x-25-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [800],
        yearRange: "2025-2026",
        yearStart: 2025,
        yearEnd: 2026,
    },
    {
        id: 93,
        name: "KOVE 800X 25-26 - Protection de cadre - Noir",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection de cadre"],
        brand: "KOVE",
        category: "Protection de cadre",
        bikeType: "Adventure",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["KOVE 800X 25-26"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/kove-800x-25-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [800],
        yearRange: "2025-2026",
        yearStart: 2025,
        yearEnd: 2026,
    },
    {
        id: 94,
        name: "KOVE 800X 25-26 - Protection de plaque latérale - Transparent",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de plaque latérale"],
        brand: "KOVE",
        category: "Protection de plaque latérale",
        bikeType: "Adventure",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["KOVE 800X 25-26"],
        inStock: true,
        color: "Transparent",
        colorHex: "#FFFFFF",
        image: "/images/products/kove-800x-25-26-protection-de-plaque-laterale-transparent.svg",
        stock: 20,
        displacements: [800],
        yearRange: "2025-2026",
        yearStart: 2025,
        yearEnd: 2026,
    },
    {
        id: 95,
        name: "TM 125-530 2T4T MX.MXFI EN.ENFI 22-26 - Protection de cadre - Gris",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "TM Racing",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["TM 125-530 2T4T MX.MXFI EN.ENFI 22-26"],
        inStock: true,
        color: "Gris",
        colorHex: "#808080",
        image: "/images/products/tm-125-530-2t4t-mx-mxfi-en-enfi-22-26-protection-de-cadre-gris.svg",
        stock: 20,
        displacements: [125, 250, 300, 450, 530],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
    {
        id: 96,
        name: "TM 125-530 2T4T MX.MXFI EN.ENFI 22-26 - Protection de cadre - Noir",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "TM Racing",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: PRODUCT_DESCRIPTION,
        features: PRODUCT_FEATURES,
        compatibility: ["TM 125-530 2T4T MX.MXFI EN.ENFI 22-26"],
        inStock: true,
        color: "Noir",
        colorHex: "#000000",
        image: "/images/products/tm-125-530-2t4t-mx-mxfi-en-enfi-22-26-protection-de-cadre-noir.svg",
        stock: 20,
        displacements: [125, 250, 300, 450, 530],
        yearRange: "2022-2026",
        yearStart: 2022,
        yearEnd: 2026,
    },
];

export default products;
