export interface Product {
    id: number
    name: string
    price: string
    priceNumber: number
    variants: string[]
    brand: string
    category: string
    bikeType: string
    description: string
    features: string[]
    compatibility: string[]
    inStock: boolean
    colors: { id: string; name: string; hex: string }[]
    image: string
    stock: number
}

export const products: Product[] = [
    {
        id: 1,
        name: "HUSQVARNA 125-300TC / 250-450FC 23-25 Grip pour protection plastique ORIGINAL",
        price: "17,99 €",
        priceNumber: 17.99,
        variants: ["Protection plastique"],
        brand: "HUSQVARNA",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Grip pour protection plastique spécialement conçu pour HUSQVARNA 125-300TC et 250-450FC modèles 2023-2025. Protection ORIGINAL offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip ORIGINAL",
            "Protection optimale des plastiques",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["HUSQVARNA 125-300TC 2023-2025", "HUSQVARNA 250-450FC 2023-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/husqvarna-grip-protection.png",
        stock: 20,
    },
    {
        id: 2,
        name: "FANTIC XXF250 21-25 / XXF450 21-25 Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "FANTIC",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour FANTIC XXF250 et XXF450 modèles 2021-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["FANTIC XXF250 2021-2025", "FANTIC XXF450 2021-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/fantic-xxf-frame-protection.png",
        stock: 15,
    },
    {
        id: 3,
        name: "HONDA CRF250R 22-25 / CRF450R 21-25 Protection de cadre",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "HONDA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour HONDA CRF250R et CRF450R modèles 2021-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["HONDA CRF250R 2022-2025", "HONDA CRF450R 2021-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/honda-crf-frame-protection.png",
        stock: 12,
    },
    {
        id: 4,
        name: "KAWASAKI 125KX 03-08 / 250KX 03-04 Protection de cadre",
        price: "15,99 €",
        priceNumber: 15.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour KAWASAKI 125KX et 250KX modèles 2003-2008. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 125KX 2003-2008", "KAWASAKI 250KX 2003-2004"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kx-frame-protection.png",
        stock: 18,
    },
    {
        id: 5,
        name: "KAWASAKI 250KXF 15-20 Protection de cadre",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour KAWASAKI 250KXF modèles 2015-2020. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2015-2020"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-frame-protection.png",
        stock: 10,
    },
    {
        id: 6,
        name: "KAWASAKI 250KXF 2025 / 450KXF 24-25 Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour KAWASAKI 250KXF 2025 et 450KXF 2024-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2025", "KAWASAKI 450KXF 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-2025-frame-protection.png",
        stock: 20,
    },
    {
        id: 7,
        name: "KAWASAKI 250KXF 21-24 / 450KXF 19-23 Protection de cadre",
        price: "25,99 €",
        priceNumber: 25.99,
        variants: ["Protection de cadre"],
        brand: "KAWASAKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour KAWASAKI 250KXF 2021-2024 et 450KXF 2019-2023. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2021-2024", "KAWASAKI 450KXF 2019-2023"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-19-24-frame-protection.png",
        stock: 12,
    },
    {
        id: 8,
        name: "KOVE 450 RALLY 24-25 Protection de cadre",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "KOVE",
        category: "Protection de cadre",
        bikeType: "Rally",
        description:
            "Protection de cadre spécialement conçue pour KOVE 450 RALLY modèles 2024-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KOVE 450 RALLY 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kove-450-rally-frame-protection.png",
        stock: 15,
    },
    {
        id: 9,
        name: "STARK MX 22-25 / EX 24-25 Protection de cadre",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de cadre"],
        brand: "STARK",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour STARK MX 2022-2025 et EX 2024-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["STARK MX 2022-2025", "STARK EX 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/stark-mx-ex-frame-protection.png",
        stock: 25,
    },
    {
        id: 10,
        name: "SUZUKI 125RM 01-12 / 250RM 01-08 Protection de cadre",
        price: "15,99 €",
        priceNumber: 15.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour SUZUKI 125RM 2001-2012 et 250RM 2001-2008. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["SUZUKI 125RM 2001-2012", "SUZUKI 250RM 2001-2008"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/suzuki-rm-frame-protection.png",
        stock: 18,
    },
    {
        id: 11,
        name: "SUZUKI 250RMZ 19-24 / 450RMZ 18-24 Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour SUZUKI 250RMZ 2019-2024 et 450RMZ 2018-2024. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["SUZUKI 250RMZ 2019-2024", "SUZUKI 450RMZ 2018-2024"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/suzuki-rmz-frame-protection.png",
        stock: 15,
    },
    {
        id: 12,
        name: "SUZUKI 450RMZ 08-17 Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "SUZUKI",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour SUZUKI 450RMZ modèles 2008-2017. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["SUZUKI 450RMZ 2008-2017"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/suzuki-rmz-08-17-frame-protection.png",
        stock: 12,
    },
    {
        id: 13,
        name: "TRIUMPH TF 250-X 24-25 Protection de cadre",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "TRIUMPH",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour TRIUMPH TF 250-X modèles 2024-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["TRIUMPH TF 250-X 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/triumph-tf-frame-protection.png",
        stock: 10,
    },
    {
        id: 41,
        name: "Protection de cadre YAMAHA 125YZ 05-24 / 250YZ 05-24",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour YAMAHA 125YZ et 250YZ modèles 2005-2024. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA 125YZ 2005-2024", "YAMAHA 250YZ 2005-2024"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz125-250-frame-protection.png",
        stock: 20,
    },
    {
        id: 42,
        name: "Protection de cadre YAMAHA YZ250F 19-23 / YZ450F 18-22",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour YAMAHA YZ250F 2019-2023 et YZ450F 2018-2022. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA YZ250F 2019-2023", "YAMAHA YZ450F 2018-2022"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz250f-450f-18-23-frame-protection.png",
        stock: 20,
    },
    {
        id: 43,
        name: "Protection de cadre YAMAHA YZ250F 24-25 / YZ450F 23-25",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "YAMAHA",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description:
            "Protection de cadre spécialement conçue pour YAMAHA YZ250F 2024-2025 et YZ450F 2023-2025. Protection offrant une adhérence maximale et une protection optimale de votre cadre.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA YZ250F 2024-2025", "YAMAHA YZ450F 2023-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz250f-450f-23-25-frame-protection.png",
        stock: 20,
    },
    {
        id: 44,
        name: "Protection de carter d'embrayage KOVE 450 RALLY 24-25",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection moteur"],
        brand: "KOVE",
        category: "Protection moteur",
        bikeType: "Rally",
        description:
            "Protection de carter d'embrayage spécialement conçu pour KOVE 450 RALLY modèles 2024-2025. Protection offrant une résistance optimale contre les chocs et frottements.",
        features: [
            "Protection renforcée du carter d'embrayage",
            "Installation facile et rapide",
            "Matériau haute résistance aux impacts",
            "Design adapté au moteur KOVE",
            "Testé en conditions rallye",
        ],
        compatibility: ["KOVE 450 RALLY 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kove-450-rally-clutch-cover-protection.png",
        stock: 30,
    },
    {
        id: 45,
        name: "Protection de carter STARK MX 22-25 / EX 24-25",
        price: "7,99 €",
        priceNumber: 7.99,
        variants: ["Protection moteur"],
        brand: "STARK",
        category: "Protection moteur",
        bikeType: "Motocross",
        description:
            "Protection de carter spécialement conçue pour STARK MX modèles 2022-2025 et EX 2024-2025. Protection offrant une résistance optimale contre les chocs et frottements.",
        features: [
            "Protection renforcée du carter",
            "Installation facile et rapide",
            "Matériau haute résistance aux impacts",
            "Design adapté au moteur STARK",
            "Testé en conditions course",
        ],
        compatibility: ["STARK MX 2022-2025", "STARK EX 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/stark-mx-ex-case-protection.jpg",
        stock: 25,
    },
    {
        id: 46,
        name: "Protection de plaque latérale HONDA CRF250R 22-25 / CRF450R 21-25",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection plastique"],
        brand: "HONDA",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour HONDA CRF250R 2022-2025 et CRF450R 2021-2025. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["HONDA CRF250R 2022-2025", "HONDA CRF450R 2021-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/honda-crf-side-plate-protection.png",
        stock: 20,
    },
    {
        id: 47,
        name: "Protection de plaque latérale KAWASAKI 250KXF 17-20",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection plastique"],
        brand: "KAWASAKI",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour KAWASAKI 250KXF modèles 2017-2020. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2017-2020"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-side-plate-protection.png",
        stock: 15,
    },
    {
        id: 48,
        name: "Protection de plaque latérale KAWASAKI 250KXF 21-24 / 450KXF 19-23",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection plastique"],
        brand: "KAWASAKI",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour KAWASAKI 250KXF 2021-2024 et 450KXF 2019-2023. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2021-2024", "KAWASAKI 450KXF 2019-2023"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-side-plate-21-24-protection.png",
        stock: 15,
    },
    {
        id: 49,
        name: "Protection de plaque latérale YAMAHA 125YZ 15-21 / 250YZ 15-21",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection plastique"],
        brand: "YAMAHA",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour YAMAHA 125YZ 2015-2021 et 250YZ 2015-2021. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA 125YZ 2015-2021", "YAMAHA 250YZ 2015-2021"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz125-250-side-plate-protection.png",
        stock: 20,
    },
    {
        id: 51,
        name: "Protection de plaque latérale YAMAHA YZ250F 24-25 / YZ450F 23-25",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection plastique"],
        brand: "YAMAHA",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour YAMAHA YZ250F 2024-2025 et YZ450F 2023-2025. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA YZ250F 2024-2025", "YAMAHA YZ450F 2023-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz250f-450f-side-plate-24-25-protection.jpg",
        stock: 20,
    },
    {
        id: 52,
        name: "Protection de plaque latéral STARK MX 22-25 / EX 24-25",
        price: "15,99 €",
        priceNumber: 15.99,
        variants: ["Protection plastique"],
        brand: "STARK",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour STARK MX 2022-2025 et EX 2024-2025. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["STARK MX 2022-2025", "STARK EX 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/stark-mx-ex-side-plate-protection.jpg",
        stock: 20,
    },
    {
        id: 53,
        name: "Protection de plaque latéral TRIUMPH TF 250-X 24-25",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection plastique"],
        brand: "TRIUMPH",
        category: "Protection plastique",
        bikeType: "Motocross",
        description:
            "Protection de plaque latérale spécialement conçue pour TRIUMPH TF 250-X 2024-2025. Grip offrant une adhérence maximale et une protection optimale de vos plastiques.",
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["TRIUMPH TF 250-X 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/triumph-tf250x-side-plate-protection.jpg",
        stock: 20,
    },
].sort((a, b) => a.brand.localeCompare(b.brand))
