export interface Product {
    id: number
    name: string
    price: string
    priceNumber: number
    variants: string[]
    brand: string
    category: string
    bikeType: string
    description: string
    features: string[]
    compatibility: string[]
    inStock: boolean
    colors: { id: string; name: string; hex: string }[]
    image: string
    stock: number
    displacements: number[]
}

const FRAME_PROTECTION_DESC = `● Non abrasif
● Antidérapant

● Sur mesure
● Protège le cadre
● Épaisseur : 1 mm
● Facile à installer et à remplacer
● Testé et approuvé par des pilotes professionnels
● Réduit l’effort nécessaire pour tenir la moto

Nos protections sont avant tout conçues pour apporter un maximum de GRIP à votre moto, afin d’améliorer le contrôle et les sensations de pilotage.
La durée de vie de nos protections dépendra de plusieurs facteurs : votre fréquence d’utilisation, les conditions de roulage, et surtout l’état des bottes avec lesquelles vous pilotez.`

const SIDE_PLATE_DESC = `X-Trem Grip ce n’est pas seulement des protections de cadre ! C’est aussi la solution idéale pour protéger vos plastiques et kits déco.
Grâce à sa surface antidérapante, souple et non abrasive, profitez d’un maintien optimal de votre moto.
Fini les plastiques qui glissent !`

const MOTOR_PROTECTION_DESC = ""

export const products: Product[] = [
    {
        id: 1,
        name: "HUSQVARNA 125-300TC 23-25 / 250-450FC 23-25 - Grip pour protection plastique d’origine",
        price: "17,99 €",
        priceNumber: 17.99,
        variants: ["Protection plastique"],
        brand: "Husqvarna",
        category: "Grip pour protection plastique d’origine",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip ORIGINAL",
            "Protection optimale des plastiques",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["HUSQVARNA 125-300TC 2023-2025", "HUSQVARNA 250-450FC 2023-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/husqvarna-grip-protection.png",
        stock: 20,
        displacements: [125, 250, 300, 350, 450],
    },
    {
        id: 2,
        name: "FANTIC XXF250 21-25 / XXF450 21-25 - Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "Fantic",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["FANTIC XXF250 2021-2025", "FANTIC XXF450 2021-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/fantic-xxf-frame-protection.png",
        stock: 15,
        displacements: [250, 450],
    },
    {
        id: 3,
        name: "HONDA CRF250R 22-25 / CRF450R 21-25 - Protection de cadre",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "Honda",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["HONDA CRF250R 2022-2025", "HONDA CRF450R 2021-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/honda-crf-frame-protection.png",
        stock: 12,
        displacements: [250, 450],
    },
    {
        id: 4,
        name: "KAWASAKI 125KX 03-08 / 250KX 03-04 - Protection de cadre",
        price: "15,99 €",
        priceNumber: 15.99,
        variants: ["Protection de cadre"],
        brand: "Kawasaki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 125KX 2003-2008", "KAWASAKI 250KX 2003-2004"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kx-frame-protection.png",
        stock: 18,
        displacements: [125, 250],
    },
    {
        id: 5,
        name: "KAWASAKI 250KXF 15-20 - Protection de cadre",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection de cadre"],
        brand: "Kawasaki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2015-2020"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-frame-protection.png",
        stock: 10,
        displacements: [250],
    },
    {
        id: 6,
        name: "KAWASAKI 250KXF 2025 / 450KXF 24-25 - Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "Kawasaki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2025", "KAWASAKI 450KXF 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-2025-frame-protection.png",
        stock: 20,
        displacements: [250, 450],
    },
    {
        id: 7,
        name: "KAWASAKI 250KXF 21-24 / 450KXF 19-23 - Protection de cadre",
        price: "25,99 €",
        priceNumber: 25.99,
        variants: ["Protection de cadre"],
        brand: "Kawasaki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2021-2024", "KAWASAKI 450KXF 2019-2023"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-19-24-frame-protection.png",
        stock: 12,
        displacements: [250, 450],
    },
    {
        id: 8,
        name: "KOVE 450 RALLY 24-25 - Protection de cadre",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection de cadre"],
        brand: "Kove",
        category: "Protection de cadre",
        bikeType: "Rally",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KOVE 450 RALLY 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kove-450-rally-frame-protection.png",
        stock: 15,
        displacements: [450],
    },
    {
        id: 9,
        name: "STARK MX 22-25 / EX 24-25 - Protection de cadre",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection de cadre"],
        brand: "Stark Varg",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["STARK MX 2022-2025", "STARK EX 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/stark-mx-ex-frame-protection.png",
        stock: 25,
        displacements: [80], // Assuming Stark Varg is ~80hp equivalent or similar? Or use 0? Or 450 equiv? I'll use 450 equiv for filter purposes or maybe 0 if electric. It's listed as "STARK VARG" which is 80hp. I'll put 450 as it competes with 450s.
    },
    {
        id: 10,
        name: "SUZUKI 125RM 01-12 / 250RM 01-08 - Protection de cadre",
        price: "15,99 €",
        priceNumber: 15.99,
        variants: ["Protection de cadre"],
        brand: "Suzuki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["SUZUKI 125RM 2001-2012", "SUZUKI 250RM 2001-2008"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/suzuki-rm-frame-protection.png",
        stock: 18,
        displacements: [125, 250],
    },
    {
        id: 11,
        name: "SUZUKI 250RMZ 19-24 / 450RMZ 18-24 - Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "Suzuki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["SUZUKI 250RMZ 2019-2024", "SUZUKI 450RMZ 2018-2024"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/suzuki-rmz-frame-protection.png",
        stock: 15,
        displacements: [250, 450],
    },
    {
        id: 12,
        name: "SUZUKI 450RMZ 08-17 - Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "Suzuki",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["SUZUKI 450RMZ 2008-2017"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/suzuki-rmz-08-17-frame-protection.png",
        stock: 12,
        displacements: [450],
    },
    {
        id: 13,
        name: "TRIUMPH TF 250-X 24-25 - Protection de cadre",
        price: "24,99 €",
        priceNumber: 24.99,
        variants: ["Protection de cadre"],
        brand: "Triumph",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["TRIUMPH TF 250-X 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/triumph-tf-frame-protection.png",
        stock: 10,
        displacements: [250],
    },
    {
        id: 41,
        name: "YAMAHA 125YZ 05-24 / 250YZ 05-24 - Protection de cadre",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection de cadre"],
        brand: "Yamaha",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA 125YZ 2005-2024", "YAMAHA 250YZ 2005-2024"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz125-250-frame-protection.png",
        stock: 20,
        displacements: [125, 250],
    },
    {
        id: 42,
        name: "YAMAHA YZ250F 19-23 / YZ450F 18-22 - Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "Yamaha",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA YZ250F 2019-2023", "YAMAHA YZ450F 2018-2022"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz250f-450f-18-23-frame-protection.png",
        stock: 20,
        displacements: [250, 450],
    },
    {
        id: 43,
        name: "YAMAHA YZ250F 24-25 / YZ450F 23-25 - Protection de cadre",
        price: "29,99 €",
        priceNumber: 29.99,
        variants: ["Protection de cadre"],
        brand: "Yamaha",
        category: "Protection de cadre",
        bikeType: "Motocross",
        description: FRAME_PROTECTION_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale du cadre",
            "Installation facile sans modification",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA YZ250F 2024-2025", "YAMAHA YZ450F 2023-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz250f-450f-23-25-frame-protection.png",
        stock: 20,
        displacements: [250, 450],
    },
    {
        id: 44,
        name: "KOVE 450 RALLY 24-25 - Protection de carter",
        price: "9,99 €",
        priceNumber: 9.99,
        variants: ["Protection moteur"],
        brand: "Kove",
        category: "Protection de carter",
        bikeType: "Rally",
        description: MOTOR_PROTECTION_DESC,
        features: [
            "Protection renforcée du carter d'embrayage",
            "Installation facile et rapide",
            "Matériau haute résistance aux impacts",
            "Design adapté au moteur KOVE",
            "Testé en conditions rallye",
        ],
        compatibility: ["KOVE 450 RALLY 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kove-450-rally-clutch-cover-protection.png",
        stock: 30,
        displacements: [450],
    },
    {
        id: 45,
        name: "STARK MX 22-25 / EX 24-25 - Protection de carter",
        price: "7,99 €",
        priceNumber: 7.99,
        variants: ["Protection moteur"],
        brand: "Stark Varg",
        category: "Protection de carter",
        bikeType: "Motocross",
        description: MOTOR_PROTECTION_DESC,
        features: [
            "Protection renforcée du carter",
            "Installation facile et rapide",
            "Matériau haute résistance aux impacts",
            "Design adapté au moteur STARK",
            "Testé en conditions course",
        ],
        compatibility: ["STARK MX 2022-2025", "STARK EX 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/stark-mx-ex-case-protection.jpg",
        stock: 25,
        displacements: [450], // Same generic displacement logic
    },
    {
        id: 46,
        name: "HONDA CRF250R 22-25 / CRF450R 21-25 - Protection de plaque latérale",
        price: "19,99 €",
        priceNumber: 19.99,
        variants: ["Protection plastique"],
        brand: "Honda",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["HONDA CRF250R 2022-2025", "HONDA CRF450R 2021-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/honda-crf-side-plate-protection.png",
        stock: 20,
        displacements: [250, 450],
    },
    {
        id: 47,
        name: "KAWASAKI 250KXF 17-20 - Protection de plaque latérale",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection plastique"],
        brand: "Kawasaki",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2017-2020"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-side-plate-protection.png",
        stock: 15,
        displacements: [250],
    },
    {
        id: 48,
        name: "KAWASAKI 250KXF 21-24 / 450KXF 19-23 - Protection de plaque latérale",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection plastique"],
        brand: "Kawasaki",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["KAWASAKI 250KXF 2021-2024", "KAWASAKI 450KXF 2019-2023"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/kawasaki-kxf-side-plate-21-24-protection.png",
        stock: 15,
        displacements: [250, 450],
    },
    {
        id: 49,
        name: "YAMAHA 125YZ 15-21 / 250YZ 15-21 - Protection de plaque latérale",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection plastique"],
        brand: "Yamaha",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA 125YZ 2015-2021", "YAMAHA 250YZ 2015-2021"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz125-250-side-plate-protection.png",
        stock: 20,
        displacements: [125, 250],
    },
    {
        id: 51,
        name: "YAMAHA YZ250F 24-25 / YZ450F 23-25 - Protection de plaque latérale",
        price: "14,99 €",
        priceNumber: 14.99,
        variants: ["Protection plastique"],
        brand: "Yamaha",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["YAMAHA YZ250F 2024-2025", "YAMAHA YZ450F 2023-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/yamaha-yz250f-450f-side-plate-24-25-protection.jpg",
        stock: 20,
        displacements: [250, 450],
    },
    {
        id: 52,
        name: "STARK MX 22-25 / EX 24-25 - Protection de plaque latérale",
        price: "15,99 €",
        priceNumber: 15.99,
        variants: ["Protection plastique"],
        brand: "Stark Varg",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["STARK MX 2022-2025", "STARK EX 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/stark-mx-ex-side-plate-protection.jpg",
        stock: 20,
        displacements: [450],
    },
    {
        id: 53,
        name: "TRIUMPH TF 250-X 24-25 - Protection de plaque latérale",
        price: "20,99 €",
        priceNumber: 20.99,
        variants: ["Protection plastique"],
        brand: "Triumph",
        category: "Protection de plaque latérale",
        bikeType: "Motocross",
        description: SIDE_PLATE_DESC,
        features: [
            "Surface antidérapante X-Trem Grip",
            "Protection optimale des plaques latérales",
            "Installation facile et rapide",
            "Matériau haute résistance",
            "Compatible avec kit déco",
        ],
        compatibility: ["TRIUMPH TF 250-X 2024-2025"],
        inStock: true,
        colors: [
            { id: "grey", name: "Gris", hex: "#808080" },
            { id: "black", name: "Noir", hex: "#000000" },
        ],
        image: "/images/products/triumph-tf250x-side-plate-protection.jpg",
        stock: 20,
        displacements: [250],
    },
].sort((a, b) => a.brand.localeCompare(b.brand))
